#!/usr/bin/env bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2006 Stephen Bennett
# Copyright (c) 2007, 2009, 2011 Ciaran McCreesh
#
# Based in part upon dodoc from Portage, which is Copyright 1995-2005
# Gentoo Foundation and distributed under the terms of the GNU General
# Public License v2.
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

source "${PALUDIS_EBUILD_DIR}"/die_functions.bash

if [[ ! -d ${!PALUDIS_IMAGE_DIR_VAR} ]]; then
    paludis_die_or_error "\${${PALUDIS_IMAGE_DIR_VAR}} not valid; aborting"
fi

recurse=false

if [[ -n ${PALUDIS_DODOC_R} ]] ; then
    if [[ $1 == "-r" ]] ; then
        shift
        recurse=true
    fi
fi

if [[ $# -lt 1 ]]; then
    paludis_die_or_error "at least one argument needed"
fi

dir="${!PALUDIS_IMAGE_DIR_VAR}usr/share/doc/${!PALUDIS_NAME_VERSION_REVISION_VAR}/${DOCDESTTREE}"
if [[ ! -d "${dir}" ]]; then
    install -d "${dir}" || paludis_die_or_error "could not create ${dir}"
fi

ret=0

for x in "$@"; do
    if $recurse && [[ -d "${x}" ]] ; then
        (
            export DOCDESTTREE="${DOCDESTTREE}/${x}"
            cd "${x}"
            ls * >/dev/null 2>&1 && dodoc -r *
        )
    elif [[ -d "${x}" ]] ; then
        echo "${0}: ${x} is a directory but we are not recursing" >&2
        ret=1
    elif [[ -s "${x}" ]]; then
        install -m0644 "${x}" "${dir}"
    elif [[ ! -e "${x}" ]]; then
        echo "${0}: ${x} does not exist" >&2
        ret=2
    fi
done

[[ 0 != "${ret}" ]] && paludis_die_or_error "dodoc returned error ${ret}"
exit ${ret}

