#!/bin/bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2006 Stephen Bennett
#
# Based in part upon doins from Portage, which is Copyright 1995-2005
# Gentoo Foundation and distributed under the terms of the GNU General
# Public License v2.
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

export PATH="${PALUDIS_EBUILD_DIR:+${PALUDIS_EBUILD_DIR}/utils:}${PATH}"

if [[ ! -d ${D} ]]; then
    echo "${0}: \${D} not valid; aborting" >&2
    exit 247
fi

if [[ ! -d ${T} ]]; then
    echo "${0}: \${T} not valid; aborting" >&2
    exit 247
fi

if [[ ${#} -lt 1 ]]; then
    echo "${0}: at least one argument needed" >&2
    exit 1
fi

if [[ ${1} == "-r" ]]; then
    DOINSRECUR=y
    shift
else
    DOINSRECUR=n
fi

if [[ -z "${INSDEPTH}" ]]; then
    declare -i INSDEPTH=0
fi

if [[ ${INSDESTTREE} == ${D}* ]]; then
    echo "-------------------------------------------------------" >&2
    echo "You should not use \${D} with helpers." >&2
    echo "  --> ${INSDESTTREE}" >&2
    echo "-------------------------------------------------------" >&2
    exit 248
fi

if [[ ! -d "${D}${INSDESTTREE}" ]]; then
    dodir "${INSDESTTREE}"
fi

ret=0

for x in "$@"; do
    if [[ -L ${x} ]]; then
        cp "${x}" "${T}"
        mysrc="${T}/$(basename "${x}")"
    elif [[ -d ${x} ]]; then
        if [[ ${DOINSRECUR} == "n" ]]; then
            continue
        fi

        mydir="${INSDESTTREE}/$(basename "${x}")"
        find "${x}" -mindepth 1 -maxdepth 1 -exec \
            env \
                INSDESTTREE="${mydir}" \
                INSDEPTH=$((INSDEPTH+1)) \
                ${0} -r {} \;
        continue
    else
        mysrc="${x}"
    fi

    install ${INSOPTIONS} "${mysrc}" "${D}${INSDESTTREE}" || ret=2
done

exit ${ret}
