#!/usr/bin/env bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2006 Stephen Bennett
#
# Based in part upon doins from Portage, which is Copyright 1995-2005
# Gentoo Foundation and distributed under the terms of the GNU General
# Public License v2.
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

source "${PALUDIS_EBUILD_DIR}"/die_functions.bash

if [[ ! -d "${!PALUDIS_IMAGE_DIR_VAR}" ]]; then
    paludis_die_or_error "\${${PALUDIS_IMAGE_DIR_VAR}} not valid; aborting"
fi

if [[ ! -d "${!PALUDIS_TEMP_DIR_VAR}" ]]; then
    paludis_die_or_error "\${${PALUDIS_TEMP_DIR_VAR}} not valid; aborting"
fi

if [[ "${#}" -lt '1' ]]; then
    paludis_die_or_error "at least one argument needed"
fi

DOINSRECUR='n'
if [[ "${1}" == '-r' ]]; then
    DOINSRECUR='y'
    shift
fi

if [[ -z "${INSDEPTH}" ]]; then
    declare -i INSDEPTH='0'
fi

if [[ ${INSDESTTREE} == ${!PALUDIS_IMAGE_DIR_VAR}* ]]; then
    echo "-------------------------------------------------------" >&2
    echo "You should not use \${${PALUDIS_IMAGE_DIR_VAR}} with helpers." >&2
    echo "  --> ${INSDESTTREE}" >&2
    echo "-------------------------------------------------------" >&2
    paludis_die_or_error
fi

if [[ ! -d "${!PALUDIS_IMAGE_DIR_VAR}${INSDESTTREE}" ]]; then
    dodir "${INSDESTTREE}"
fi

ret='0'

for x in "$@"; do
    if [[ -L "${x}" ]]; then
        if [[ -n "${PALUDIS_DOINS_SYMLINK}" ]] ; then
            ln -s "$(readlink "${x}" )" "${!PALUDIS_IMAGE_DIR_VAR}${INSDESTTREE}/$(basename "${x}")" || ret='2'
            continue
        else
            cp "${x}" "${!PALUDIS_TEMP_DIR_VAR}"
            mysrc="${!PALUDIS_TEMP_DIR_VAR}/$(basename "${x}")"
        fi
    elif [[ -d "${x}" ]]; then
        if [[ "${DOINSRECUR}" == 'n' ]]; then
            continue
        fi

        mydir="${INSDESTTREE}/$(basename "${x}")"
        find "${x}" -mindepth '1' -maxdepth '1' -exec \
            env \
                INSDESTTREE="${mydir}" \
                INSDEPTH=$((INSDEPTH+1)) \
                ${0} -r {} \;
        continue
    else
        mysrc="${x}"
    fi

    install ${INSOPTIONS} "${mysrc}" "${!PALUDIS_IMAGE_DIR_VAR}${INSDESTTREE}" || ret='2'
done

[[ '0' != "${ret}" ]] && paludis_die_or_error "doins returned error ${ret}"
exit "${ret}"
