#!/usr/bin/env bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2006 Stephen Bennett
#
# Based in part upon doman from Portage, which is Copyright 1995-2005
# Gentoo Foundation and distributed under the terms of the GNU General
# Public License v2.
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

source "${PALUDIS_EBUILD_DIR}"/die_functions.bash
source "${PALUDIS_EBUILD_DIR}"/0/list_functions.bash

if [[ ! -d ${!PALUDIS_IMAGE_DIR_VAR%/}/ ]]; then
    paludis_die_or_error "\${${PALUDIS_IMAGE_DIR_VAR}} not valid; aborting"
fi

if [[ ${#} -lt 1 ]]; then
    paludis_die_or_error "at least one argument needed"
fi

BASE="/usr/share"
i18n=""
ret=0

for x in "$@"; do
    if [[ ${x:0:6} == "-i18n=" ]]; then
        i18n="${x:6}/"
        continue
    fi
    if [[ ${x} == .keep_* ]]; then
        continue
    fi

    suffix=${x##*.}

    if has ${suffix} Z gz bz2; then
        realname=${x%.*}
        suffix=${realname##*.}
    fi

    if [[ -n ${PALUDIS_DOMAN_LANG_FILENAMES_OVERRIDES} && -n ${i18n} ]] ; then
        name=${x##*/}
        mandir=${i18n}man${suffix:0:1}
    elif [[ -n ${PALUDIS_DOMAN_LANG_FILENAMES} && \
            $x =~ (.*)\.([a-z][a-z](_[A-Z][A-Z])?)\.(.*) ]] ; then
        name=${BASH_REMATCH[1]##*/}.${BASH_REMATCH[4]}
        mandir=${BASH_REMATCH[2]}/man${suffix:0:1}
    else
        name=${x##*/}
        mandir=${i18n}man${suffix:0:1}
    fi

    match='man[0-9n](|f|p|pm)$'

    if [[ ${mandir} =~ ${match} ]]; then
        if [[ -s ${x} ]]; then
            if [[ ! -d "${!PALUDIS_IMAGE_DIR_VAR%/}/${BASE#/}/man/${mandir}" ]]; then
                install -d "${!PALUDIS_IMAGE_DIR_VAR%/}/${BASE#/}/man/${mandir}"
            fi

            install -m0644 "${x}" "${!PALUDIS_IMAGE_DIR_VAR%/}/${BASE#/}/man/${mandir}/${name}" || ret=2
        elif [[ ! -e ${x} ]]; then
            echo "${0}: ${x} does not exist" >&2
            ret=2
        fi
    else
        echo "${0}: '${x}' is probably not a man page; skipping" >&2
        ret=2
    fi
done

[[ 0 != "${ret}" ]] && paludis_die_or_error "doman returned error ${ret}"
exit ${ret}
