#!/bin/bash

if /bin/sed --version &>/dev/null ; then
    /bin/sed "$@"
    exit $?
elif /usr/bin/sed --version &>/dev/null ; then
    /usr/bin/sed "$@"
    exit $?
elif /usr/local/bin/sed --version &>/dev/null ; then
    /usr/local/bin/sed "$@"
    exit $?
elif gsed --version &>/dev/null ; then
    gsed "$@"
    exit $?
else
    echo "!!! Don't know how to use GNU sed on this system" 1>&2
    exit 1
fi

