#!/usr/bin/env bash

case $(uname -s) in
    FreeBSD)
    stat -f '%m' "$@"
    exit $?
    ;;

    Linux)
    mtime=$(stat -c '%Y' "$@")
    ret=$?
    echo ${mtime%%.*}
    exit $ret
    ;;

    *)
    echo "!!! Don't know how to use stat on this system" 1>&2
    exit $?
    ;;
esac

