#!/usr/bin/env bash

export PALUDIS_HOME=`pwd`/continue_on_failure_TEST_dir/config/
export TEST_ROOT=`pwd`/continue_on_failure_TEST_dir/root/

./cave --environment :continue-on-failure-test \
        resolve -x --continue-on-failure if-satisfied a b c

if [[ -f continue_on_failure_TEST_dir/root/a ]] ; then
    exit 1
fi

if [[ -f continue_on_failure_TEST_dir/root/b ]] ; then
    exit 2
fi

if ! [[ -f continue_on_failure_TEST_dir/root/c ]] ; then
    exit 3
fi

if [[ -f continue_on_failure_TEST_dir/root/d ]] ; then
    exit 4
fi

if ! [[ -f continue_on_failure_TEST_dir/root/e ]] ; then
    exit 5
fi

./cave --environment :continue-on-failure-test \
        resolve -x =cat/w-1 cat/u --permit-old-version '*/*' || exit 6

./cave --environment :continue-on-failure-test \
        resolve -x --continue-on-failure if-independent x y z

if [[ -f continue_on_failure_TEST_dir/root/z ]] ; then
    exit 7
fi

if [[ -f continue_on_failure_TEST_dir/root/y ]] ; then
    exit 8
fi

if ! [[ -f continue_on_failure_TEST_dir/root/x ]] ; then
    exit 9
fi

if [[ -f continue_on_failure_TEST_dir/root/w ]] ; then
    exit 10
fi

if ! [[ -f continue_on_failure_TEST_dir/root/v ]] ; then
    exit 11
fi

exit 0

