#!/bin/bash

cat <<"EOF"
         _________________________________
        / Unknown command 'moo'           \
        \ (paludis::cave::UnknownCommand) /
         ---------------------------------
                \   ^__^
                 \  (oo)\_______
                    (__)\       )\/\
                        ||----w |
                        ||     ||
EOF

