#!/bin/bash

PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --config-suffix install-test \
    --has-version test-category/target && exit 1
PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --config-suffix install-test \
    --install target || exit 2
./install_TEST_dir/root/usr/bin/testbin | grep success >/dev/null || exit 3
PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --config-suffix install-test \
    --has-version test-category/target || exit 4

