#!/bin/bash

for c in vdb_config exndbam_config ; do

    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --list-packages || exit 12

    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --query test-category/target || exit 13

    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --has-version test-category/target && exit 1
    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --install target --resume-command-template `pwd`/install_TEST_dir/resume \
        --checks always && exit 2
    ( echo -n './paludis ' ; cut -d ' ' -f2- < install_TEST_dir/resume ) > install_TEST_dir/fixedresume
    cat install_TEST_dir/fixedresume
    PALUDIS_HOME=./install_TEST_dir/config/ bash `pwd`/install_TEST_dir/fixedresume --checks none || exit 3
    ./install_TEST_dir/root/usr/bin/testbin | grep success >/dev/null || exit 4
    grep target install_TEST_dir/root/world-${c%_config} || exit 5
    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --has-version test-category/target || exit 6
    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --contents test-category/target || exit 12
    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --uninstall target || exit 7
    [[ -f ./install_TEST_dir/root/usr/bin/testbin ]] && exit 8
    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        --has-version test-category/target && exit 9
    grep target install_TEST_dir/root/world-${c%_config} >/dev/null && exit 10

    PALUDIS_HOME=./install_TEST_dir/config/ ./paludis --environment :install-test-$c \
        -qMD test-category/target || exit 11

    rm -fr install_TEST_dir/root/usr/{share/doc,bin}
done

true

