#!/bin/bash

PALUDIS_HOME=./pretend_TEST_dir/config/ ./paludis --environment :pretend-test \
    --list-packages || exit 12

PALUDIS_HOME=./pretend_TEST_dir/config/ ./paludis --environment :pretend-test \
    --query test-category/target || exit 13

PALUDIS_HOME=./pretend_TEST_dir/config/ ./paludis --environment :pretend-test \
    --has-version test-category/target && exit 1

export PRETEND_SHOULD_FAIL=yes

PALUDIS_HOME=./pretend_TEST_dir/config/ ./paludis --environment :pretend-test \
    --pretend --install test-category/target && exit 2

PALUDIS_HOME=./pretend_TEST_dir/config/ ./paludis --environment :pretend-test \
    --install test-category/target && exit 3

export PRETEND_SHOULD_FAIL=

PALUDIS_HOME=./pretend_TEST_dir/config/ ./paludis --environment :pretend-test \
    --pretend --install test-category/target || exit 4

PALUDIS_HOME=./pretend_TEST_dir/config/ ./paludis --environment :pretend-test \
    --install test-category/target || exit 5


