#!/bin/bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2007 Ciaran McCreesh <ciaranm@ciaranm.org>
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License version 2, as published by the Free Software Foundation.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

eselect_env_update_TEST()
{
    export ROOT=`pwd`/eselect_env_update_TEST_dir
    export PALUDIS_LIVE_DESTINATION=
    mkdir -p eselect_env_update_TEST_dir/{etc,lib}
    touch eselect_env_update_TEST_dir/etc/ld.so.conf

    ./eselect_env_update.bash >/dev/null ; test_return_code

    [[ -f eselect_env_update_TEST_dir/etc/ld.so.cache ]] ; test_return_code
}

