#!/usr/bin/env bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2007, 2008, 2009 Ciaran McCreesh
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License version 2, as published by the Free Software Foundation.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

news_none_TEST()
{
    export ROOT=`pwd`/news_TEST_dir
    export PALUDIS_LIVE_DESTINATION=
    export HOOK=sync_all_post
    export PALUDIS_HOME=`pwd`/news_TEST_dir/one
    export PACKAGE_MANAGER="paludis" ESELECT_PACKAGE_MANAGER="paludis"

    bash ${PALUDIS_HOOKER_DIR}/hooker.bash ${TOP_BUILDDIR}/hooks/news.hook hook_run_sync_all_post >/dev/null ; test_return_code
    bash ${PALUDIS_HOOKER_DIR}/hooker.bash ${TOP_BUILDDIR}/hooks/news.hook hook_run_sync_all_post \
        | grep "No unread news items found" >/dev/null ; test_return_code
}

news_one_TEST()
{
    export ROOT=`pwd`/news_TEST_dir
    export PALUDIS_LIVE_DESTINATION=
    export HOOK=sync_all_post
    export PALUDIS_HOME=`pwd`/news_TEST_dir/two
    export PACKAGE_MANAGER="paludis" ESELECT_PACKAGE_MANAGER="paludis"

    bash ${PALUDIS_HOOKER_DIR}/hooker.bash ${TOP_BUILDDIR}/hooks/news.hook hook_run_sync_all_post 2>/dev/null ; test_return_code
    bash ${PALUDIS_HOOKER_DIR}/hooker.bash ${TOP_BUILDDIR}/hooks/news.hook hook_run_sync_all_post 2>&1 \
        | grep "You have 1 unread news item" >/dev/null ; test_return_code
}

