#!/bin/bash

./archtool --find-stable-candidates -D find_stable_candidates_TEST_dir/ best | \
    tee find_stable_candidates_TEST_dir/out1.txt

if grep --silent '^ ' find_stable_candidates_TEST_dir/out1.txt ; then
    echo "out1 failed" 1>&2
    exit 127
fi

./archtool --find-stable-candidates -D find_stable_candidates_TEST_dir/ one | \
    tee find_stable_candidates_TEST_dir/out2.txt

if [[ $(grep --count '^ ' find_stable_candidates_TEST_dir/out2.txt ) != "1" ]] ; then
    echo "out2 failed" 1>&2
    exit 127
fi

