#!/usr/bin/env bash

# ebuild.bash doesn't allow USE etc to be set in user settings. But we need
# to source make.conf to pick up things like CFLAGS.
unset paludis_check_save_vars paludis_check_unmodifiable_vars

