#!/bin/bash

# ebuild.bash doesn't allow USE etc to be set in user settings. But we need
# to source make.conf to pick up things like CFLAGS. So... After sourcing
# make.conf, unset things that ebuild.bash disallows.
unset ${save_vars}

