#!/bin/bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2006 Stephen Bennett <spb@gentoo.org>
#
# Based in part upon dolib from Portage, which is Copyright 1995-2005
# Gentoo Foundation and distributed under the terms of the GNU General
# Public License v2.
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

if [[ ! -d ${D} ]]; then
    echo "${0}: \${D} not valid; aborting" >&2
    exit 247
fi

if [[ ! -d ${PALUDIS_EBUILD_MODULES_DIR} ]]; then
    echo "${0}: \${PALUDIS_EBUILD_MODULES_DIR} not valid; aborting" >&2
    exit 1
fi

source "${PALUDIS_EBUILD_MODULES_DIR}/multilib_functions.bash"

libdir="${D}${DESTTREE}/$(ebuild_get_libdir)"

if [[ ${#} -lt 1 ]]; then
    echo "${0}: at least one argument needed"
    exit 1
fi

if [[ ! -d ${libdir} ]]; then
    install -d "${libdir}" || exit 3
fi

ret=0

for x in "$@"; do
    if [[ -e ${x} ]]; then
        if [[ ! -L ${x} ]]; then
            install ${LIBOPTIONS} "${x}" "${libdir}" || ret=2
        else
            ln -s "$(readlink "${x}")" "${libdir}/$(basename "${x}")" || ret=2
        fi
    else
        echo "${0}: ${x} does not exist"
        ret=2
    fi
done

exit ${ret}
