#!/bin/bash
# vim: set sw=4 sts=4 et :

# Copyright (c) 2006 Stephen Bennett <spb@gentoo.org>
#
# Based in part upon doman from Portage, which is Copyright 1995-2005
# Gentoo Foundation and distributed under the terms of the GNU General
# Public License v2.
#
# This file is part of the Paludis package manager. Paludis is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

if [[ ! -d ${D} ]]; then
    echo "${0}: \${D} not valid; aborting" >&2
    exit 247
fi

if [[ ${#} -lt 1 ]]; then
    echo "${0}: at least one argument needed" >&2
    exit 1
fi

if [[ -z ${PALUDIS_COMPRESS} ]]; then
    PALUDIS_COMPRESS="gzip -f -9"
fi

BASE="/usr/share"
i18n=""

for x in "$@"; do
    if [[ ${x:0:6} == "-i18n=" ]]; then
        i18n="${x:6}/"
        continue
    fi
    if [[ ${x} == .keep ]]; then
        continue
    fi

    suffix=${x##*.}

    if [[ ${suffix} == "gz" ]]; then
        compressed="gz"
        realname=${x%.*}
        suffix=${realname##*.}
    else
        realname=${x}
        compressed=""
    fi

    mandir="${i18n}man${suffix:0:1}"

    if [[ ${mandir} =~ 'man[0-9n](|f|p|pm)$' ]]; then
        if [[ -s ${x} ]]; then
            if [[ ! -d "${D}${BASE}/man/${mandir}" ]]; then
                install -d "${D}${BASE}/man/${mandir}"
            fi

            install -m0644 "${x}" "${D}${BASE}/man/${mandir}" || ret=2

            if [[ -z ${compressed} ]]; then
                ${PALUDIS_COMPRESS} "${D}${BASE}/man/${mandir}/$(basename "${x}")"
            fi
        else
            echo "${0}: ${x} does not exist" >&2
            ret=2
        fi
    else
        echo "${0}: '${x}' is probably not a man page; skipping" >&2
        ret=2
    fi
done

exit ${ret}
